# version: "3.9"

# services:
#   backend:
#     build:
#       context: ./logicflow-backend
#       dockerfile: Dockerfile
#     ports:
#       - "8000:8000"

#   frontend:
#     build:
#       context: ./logicflow-frontend-v2
#       dockerfile: Dockerfile
#     volumes:
#       - ./logicflow-frontend-v2:/logicflow-frontend-v2
#       - /logicflow-frontend-v2/node_modules
#     links:
#       - backend

#     ports:
#       - "3000:3000"

services:
  backend:
    build:
      context: ./logicflow-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./logicflow-frontend-v2
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
    depends_on:
      - backend
    networks:
      - app-network
    # Remove problematic volume mounts for now
    # volumes:
    #   - ./logicflow-frontend-v2:/logicflow-frontend-v2
    #   - /logicflow-frontend-v2/node_modules

networks:
  app-network:
    driver: bridge
